apiVersion: v1
kind: Pod
metadata:
  name: spring-cloud-order-service
  namespace: spring-cloud-example
spec:
  containers:
  - name: spring-cloud-order-service
    image: benweizhu/kubernetes-spring-cloud-order-service
    resources:
      limits:
        memory: "256Mi"
        cpu: "1"
      requests:
        memory: "128Mi"
        cpu: "0.5"