apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-cloud-order-service
  name: spring-cloud-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-order-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-cloud-order-service
    spec:
      containers:
      - image: benweizhu/kubernetes-spring-cloud-order-service
        name: kubernetes-spring-cloud-order-service
        resources: {}
status: {}
