apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-cloud-order-service
  name: spring-cloud-order-service
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-cloud-order-service
  type: LoadBalancer
status:
  loadBalancer: {}